#baseURL: "henuzxy.github.io"
title: XiaoYu Zhao
paginate: 10
theme: PaperMod
defaultContentLanguage: zh

menu:
  main:
  - identifier: archive
    name: Archive
    url: /posts/
    weight: 1
  - identifier: gibberish
    name: 胡言乱语
    url: /gibberish/
    weight: 2
  - identifier: about
    name: About Me
    pre: <i class='fa fa-heart'></i>
    url: /about/
    weight: 110
params:
    homeInfoParams:
        Title: XiaoYu Zhao
        Content: >
            Software Engineer.

            - currently working at Shopee, Living in Singapore, worked at Tencent.
            
            - Record algorithm learning, and some daily.

    socialIcons: # optional
        - name: Github
          url: https://github.com/henuzxy
        - name: LinkedIn
          url: https://www.linkedin.com/in/zhao-xiaoyu-ba30571a7/
        - name: Twitter
          url: https://twitter.com/zxy61707050
        
          